apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/arouene/test-charts.git
    targetRevision: main
    path: argocd/kustomize
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
