apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.arouene.lucca.io
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: 037650349f83c30d6eba
        clientSecret: $argocd-secret-custom:dex.github.clientSecret
        orgs:
        - name: LuccaSA
          teams:
          - Ops
  webhook.github.secret: "$argocd-secret-custom:webhook.github.secret"
  resource.exclusions: |
    - apiGroups:
      - "cilium.io"
      kinds:
      - "CiliumIdentity"
      clusters:
      - "*"
