apiVersion: v2
name: cert-manager
description: A Helm chart for Cert-Manager

type: application

version: 0.1.0
appVersion: "1.0"

dependencies:
- name: cert-manager
  version: v1.14.4
  repository: https://charts.jetstack.io
