cert-manager:
  installCRDs: true
  replicaCount: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  webhook:
    replicaCount: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
  cainjector:
    enabled: false
